#pragma once

#define EOK               0

#define E2BIG             1
#define EACCES            2
#define EADDRINUSE        3
#define EADDRNOTAVAIL     4
#define EADV              5
#define EAFNOSUPPORT      6
#define EAGAIN            7
#define EALREADY          8
#define EBADE             9
#define EBADF            10
#define EBADFD           11
#define EBADMSG          12
#define EBADR            13
#define EBADRQC          14
#define EBADSLT          15
#define EBFONT           16
#define EBUSY            17
#define ECANCELED        18
#define ECHILD           19
#define ECHRNG           20
#define ECOMM            21
#define ECONNABORTED     22
#define ECONNREFUSED     23
#define ECONNRESET       24
#define EDEADLK          25
#define EDEADLOCK        EDEADLK
#define EDESTADDRREQ     26
#define EDOM             27
#define EDOTDOT          28
#define EDQUOT           29
#define EEXIST           30
#define EFAULT           31
#define EFBIG            32
#define EHOSTDOWN        33
#define EHOSTUNREACH     34
#define EHWPOISON        35
#define EIDRM            36
#define EILSEQ           37
#define EINPROGRESS      38
#define EINTR            39
#define EINVAL           40
#define EIO              41
#define EISCONN          42
#define EISDIR           43
#define EISNAM           44
#define EKEYEXPIRED      45
#define EKEYREJECTED     46
#define EKEYREVOKED      47
#define EL2HLT           48
#define EL2NSYNC         49
#define EL3HLT           50
#define EL3RST           51
#define ELIBACC          52
#define ELIBBAD          53
#define ELIBEXEC         54
#define ELIBMAX          55
#define ELIBSCN          56
#define ELNRNG           57
#define ELOOP            58
#define EMEDIUMTYPE      59
#define EMFILE           60
#define EMLINK           61
#define EMSGSIZE         62
#define EMULTIHOP        63
#define ENAMETOOLONG     64
#define ENAVAIL          65
#define ENETDOWN         66
#define ENETRESET        67
#define ENETUNREACH      68
#define ENFILE           69
#define ENOBUFS          70
#define ENODATA          71
#define ENODEV           72
#define ENOENT           73
#define ENOEXEC          74
#define ENOKEY           75
#define ENOLCK           76
#define ENOLINK          77
#define ENOMEDIUM        78
#define ENOMEM           79
#define ENOMSG           80
#define ENONET           81
#define ENOPKG           82
#define ENOPROTOOPT      83
#define ENOANO           84
#define ENOSPC           85
#define ENOSR            86
#define ENOSTR           87
#define ENOSYS           88
#define ENOTBLK          89
#define ENOTCONN         90
#define ENOTDIR          91
#define ENOTEMPTY        92
#define ENOTNAM          93
#define ENOTRECOVERABLE  94
#define ENOTSOCK         95
#define ENOTSUP          EOPNOTSUPP
#define ENOTTY           96
#define ENOTUNIQ         97
#define ENXIO            98
#define EOPNOTSUPP       99
#define EOVERFLOW       100
#define EOWNERDEAD      101
#define EPERM           102
#define EPFNOSUPPORT    103
#define EPIPE           104
#define EPROTO          105
#define EPROTONOSUPPORT 106
#define EPROTOTYPE      107
#define ERANGE          108
#define EREMCHG         109
#define EREMOTE         110
#define EREMOTEIO       111
#define ERESTART        112
#define ERFKILL         113
#define EROFS           114
#define ESHUTDOWN       115
#define ESOCKTNOSUPPORT 116
#define ESPIPE          117
#define ESRCH           118
#define ESRMNT          119
#define ESTRPIPE        120
#define ESTALE          121
#define ETIME           122
#define ETIMEDOUT       123
#define ETOOMANYREFS    124
#define ETXTBSY         125
#define EUCLEAN         126
#define EUNATCH         127
#define EUSERS          128
#define EWOULDBLOCK     EAGAIN
#define EXDEV           129
#define EXFULL          130
