#pragma once

#define CEIL(VALUE, GRAN) (((VALUE) + (GRAN) - 1) / (GRAN) * (GRAN))

#define FLOOR(VALUE, GRAN) ((VALUE) / (GRAN) * (GRAN))

#define MIN(VALUE1, VALUE2) (VALUE1 < VALUE2 ? VALUE1 : VALUE2)

#define MAX(VALUE1, VALUE2) (VALUE1 > VALUE2 ? VALUE1 : VALUE2)
